"""Snap misheard medical terms in an STT transcript back onto a known lexicon.

The medical STT (omi-med-stt) is a greedy RNNT transducer: no beam search, no hotword
biasing, no prompt conditioning. When it mishears a drug name, the result is phonetically
close but wrong -- "met formin", "a tour of statin", "lice in a pril" -- and nothing
upstream can be told to prefer the real word. This fixes it after the fact, on the text.
Condition names fail identically ("a trial fibrillation", "my cardial infarction") and are
corrected by the same pass; see `from_files` for why they are a separate data file.

Approach: every 1-5 word window of the transcript is folded to a crude phonetic key
(lowercase letters only, common English spelling variants collapsed) and compared to the
folded lexicon with `difflib`. A window that scores at or above `THRESHOLD` against some
drug is replaced by that drug's canonical spelling. Best score wins, so "insulin
glargine" is matched as a phrase rather than as "insulin" plus a stray word.

Deliberately stdlib-only and deliberately small: a few hundred names and three window
sizes is a few thousand cheap comparisons per utterance. Swap `fold()` for a real Double
Metaphone if precision on a bigger lexicon ever needs it; nothing else has to change.

Everything that is not a match is left byte-for-byte alone, including punctuation, so
the transcript the user sees is still the transcript the model produced.
"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass
from difflib import SequenceMatcher
from pathlib import Path

_DATA = Path(__file__).with_name("data")
DEFAULT_LEXICON = _DATA / "drugs.txt"
DEFAULT_INGREDIENTS = _DATA / "ingredients.txt"
DEFAULT_CONDITIONS = _DATA / "conditions.txt"
# What agent.py loads unless MEDICAL_LEXICON overrides it. Three files because they are
# curated three different ways, not because the matcher cares:
#   drugs.txt       hand-picked commons, and the only place brand names live (see below)
#   ingredients.txt every FDA active ingredient, generated by scripts/build_drug_lexicon.py
#   conditions.txt  hand-picked conditions; they fail like drug names ("a trial
#                   fibrillation", "my cardial infarction") and needed no matcher change
# The FDA's 5228 *brand* names are deliberately not here. Measured on 101 ordinary
# sentences: ingredients corrupt 0, brands corrupt 6 ("for the" -> Forteo, "the oven" ->
# Theovent, "violin" -> V-cillin). Brands are short and English-shaped in a way generic
# names are not, so no threshold separates them -- the ones patients say are in drugs.txt
# by hand instead. Rebuild with `build_drug_lexicon.py --no-brands`.
DEFAULT_LEXICONS = (DEFAULT_LEXICON, DEFAULT_INGREDIENTS, DEFAULT_CONDITIONS)

# Similarity below which a window is not a drug. 0.8 keeps "a tour of statin" (0.80
# against atorvastatin) and drops "a tour of the city". Tune against real transcripts,
# not intuition -- see test_drug_lexicon.py for the cases it was set on.
THRESHOLD = 0.8
MAX_WINDOW = 5
# Windows shorter than this after folding are never corrected: "ali", "met", "a" are far
# more likely to be English than a truncated drug name.
MIN_KEY_LEN = 5
# A window and a drug must be within this ratio of each other's folded length.
LENGTH_RATIO = 0.8
# Folded names shorter than this are matched exactly, never fuzzily.
MIN_FUZZY_LEN = 6
# A short window needs to score higher than a long one. Rationale: a four-word window that
# happens to fold to within 20% of one drug ("lice in a pril") is a coincidence English does
# not produce, but a two-word one ("really nice", "to mention") is -- there are only so many
# ways to say two short words. Measured on 101 ordinary sentences against the 3.5k-name FDA
# ingredient list: at a flat 0.8 that list corrupted "really nice" -> repaglinide (0.800) and
# "to mention" -> tolmetin (0.824); at 0.85 for <=2 words both are rejected and every true
# positive survives, because the genuine short ones are exact fold matches ("met formin" ->
# metformin, 1.000). Raising the flat THRESHOLD instead would drop "a tour of statin", which
# also scores exactly 0.800.
SHORT_WINDOW = 2
SHORT_WINDOW_THRESHOLD = 0.85
# Consonant skeletons shorter than this are too generic to match on.
MIN_SKELETON_LEN = 4

_VOWELS = re.compile(r"[aeiou]")

# A single word that is not English at all gets the plain THRESHOLD rather than the stricter
# SHORT_WINDOW_THRESHOLD. The reasoning the short-window rule is built on -- "there are only
# so many ways to say two short words" -- does not apply to a token that is not a word: when
# the STT emits "humera" or "pridnisome" it was not transcribing English, it was guessing at
# something it did not know, and that is exactly when the lexicon should lean in. Measured on
# three synthetic voices: every term lost to a single-word mishear was a non-word, while 9 of
# the 10 English words that caused false positives are in this list.
#
# Optional by design. It is a system file, absent on some Linuxes and in the token-server
# image, and the fallback (an empty set, so every window is treated as English and held to
# the strict bar) is the conservative direction -- it can only cost recall, never precision.
_WORDLIST = Path("/usr/share/dict/words")


def _english() -> frozenset[str]:
    try:
        return frozenset(w.strip().lower() for w in _WORDLIST.read_text().splitlines() if w)
    except OSError:
        return frozenset()


_ENGLISH = _english()

_WORD = re.compile(r"[A-Za-z][A-Za-z'-]*")

# Ordered: multi-char folds first so "ph" is not seen as "p" + "h".
_FOLDS = (
    ("ph", "f"),
    ("ck", "k"),
    ("qu", "kw"),
    ("wh", "w"),
    ("gh", ""),
    ("x", "ks"),
    ("z", "s"),
)
# Soft c ("lice", "cillin") sounds like s; hard c like k. Applied after the table so "ck"
# is already gone, and before y->i so the lookahead still sees the y.
_SOFT_C = re.compile(r"c(?=[eiy])")
# Folded prefixes whose first letter is inaudible: x -> "ks", and silent p/k/w.
_SILENT_STARTS = ("ks", "ps", "kn", "wr")


def fold(text: str) -> str:
    """Collapse a word or phrase to a spelling-insensitive key.

    Not a phonetic algorithm -- just the handful of English spelling alternations an ASR
    actually produces, plus doubled-letter collapse. Vowels are kept, because for drug
    names they carry most of the signal ("lisinopril" vs "losartan").
    """
    s = "".join(ch for ch in text.lower() if ch.isalpha())
    for src, dst in _FOLDS:
        s = s.replace(src, dst)
    s = _SOFT_C.sub("s", s).replace("c", "k").replace("y", "i")
    return re.sub(r"(.)\1+", r"\1", s)


def skeleton(text: str) -> str:
    """`fold` with the vowels dropped -- the consonant spine of a word.

    `fold` keeps vowels because they separate drug names from each other. But the errors a
    transducer actually makes on an unfamiliar word are overwhelmingly *vowel* errors, and
    those survive folding: measured on real audio, "enoxaparin" came back "anoxoperin" and
    "Ozempic" came back "azampic", both scoring ~0.72 -- far below any threshold that is
    safe for English. Their consonant spines are identical ("nksprn", "smpk").

    Used only as a last-resort tier in `best()`, and only for single-word windows: across a
    multi-word window the spine stops being evidence and starts being coincidence ("my
    cousin" -> amikacin, "the main" -> thiamine, both measured).

    Matched exactly, never fuzzily -- this was tried and rejected. Scoring spines with
    SequenceMatcher at 0.85, gated on the window containing a non-word, recovers three more
    real terms ("a pramilis" -> apremilast, "duper lumab" -> dupilumab, "clarnadine" ->
    clonidine) and costs ten false positives over the same 109 non-medical sentences:
    "delivered" -> delavirdine, "practises" -> pertussis, "collects" -> colitis, "batteries
    in" -> bacitracin. Dropping the vowels throws away too much to then also allow consonant
    edits, and the non-word gate leaks on British spellings and plurals the wordlist lacks.
    A wrong drug name is worse than a missing one, so the tier stays exact.
    """
    return _VOWELS.sub("", fold(text))


@dataclass(frozen=True)
class Correction:
    start: int
    end: int
    heard: str
    drug: str
    score: float
    # Which tier matched: "fuzzy" (vowels agreed) or "spine" (consonants only). A spine hit
    # is the weakest evidence this module acts on -- it threw the vowels away to get there --
    # and is what MEDICAL_CONFIRM in agent.py offers to read back to the user.
    tier: str = "fuzzy"

    @property
    def certain(self) -> bool:
        return self.tier == "fuzzy" and self.score >= 1.0


class DrugLexicon:
    def __init__(self, names: list[str], *, threshold: float = THRESHOLD) -> None:
        self._threshold = threshold
        # (folded key, canonical spelling); exact-key lookup short-circuits the fuzzy scan.
        self._entries = [(fold(n), n) for n in names if fold(n)]
        self._exact = {k: n for k, n in self._entries}
        # Fuzzy candidates, blocked by (first letter, folded length). The length-ratio
        # guard in best() already rejects anything outside +/-20% in length, and an ASR
        # rarely mishears the first consonant, so a window only ever needs the handful of
        # blocks it could match -- ~1/500th of a 10k-name list instead of all of it.
        # Names below MIN_FUZZY_LEN are exact-only: too many short drug names are also
        # English words for a near miss to mean anything.
        self._blocks: dict[tuple[str, int], list[tuple[str, str]]] = {}
        for k, n in self._entries:
            if len(k) < MIN_FUZZY_LEN:
                continue
            self._blocks.setdefault((k[0], len(k)), []).append((k, n))
            # A leading letter the ear doesn't get: "Xanax" is heard "zanax" (folded
            # "sanaks"), "psyllium" as "silium". File those under the sound too.
            if k[:2] in _SILENT_STARTS:
                self._blocks.setdefault((k[1], len(k)), []).append((k, n))
        # Consonant spine -> the names sharing it. A spine shared by two *different* drugs
        # (escitalopram/citalopram, ciprofloxacin/sparfloxacin) is dropped rather than
        # guessed: picking the wrong one of a near-homophone pair is the worst outcome this
        # module can produce, much worse than leaving the transcript alone.
        spines: dict[str, set[str]] = {}
        for k, n in self._entries:
            if len(k) >= MIN_FUZZY_LEN:
                spines.setdefault(skeleton(n), set()).add(n)
        self._spines = {s: next(iter(v)) for s, v in spines.items() if len(v) == 1}

    @staticmethod
    def _read(path: Path) -> list[str]:
        return [
            line.strip()
            for line in path.read_text().splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ]

    @classmethod
    def from_file(cls, path: Path = DEFAULT_LEXICON, **kw) -> DrugLexicon:
        return cls(cls._read(path), **kw)

    @classmethod
    def from_files(cls, *paths: Path, **kw) -> DrugLexicon:
        """One lexicon from several files.

        Drugs and conditions live in separate files because they are curated differently
        -- data/drugs.txt is generated from Drugs@FDA, data/conditions.txt is hand-picked --
        but they share one matcher: a window of transcript is scored against every name at
        once, so "he has a trial fibrillation" and "I take met formin" cost the same scan.
        Duplicates across files are harmless; the folded key just maps to one spelling.
        """
        names: list[str] = []
        for path in paths:
            names += cls._read(path)
        return cls(names, **kw)

    def __len__(self) -> int:
        return len(self._entries)

    def best(
        self, key: str, *, words: int = MAX_WINDOW, text: str = ""
    ) -> tuple[str, float, str] | None:
        """Closest lexicon entry to a folded key, or None.

        `words` is how many transcript words the key came from; short windows are held to
        SHORT_WINDOW_THRESHOLD (see its comment). It defaults to the permissive end so a
        direct caller asking about a bare key gets the plain THRESHOLD behaviour. `text` is
        the raw window, needed only to ask whether a one-word window is English at all.
        """
        if len(key) < MIN_KEY_LEN:
            return None
        if key in self._exact:
            return self._exact[key], 1.0, "fuzzy"
        strict = words <= SHORT_WINDOW and not self._is_nonword(text, words)
        floor = max(self._threshold, SHORT_WINDOW_THRESHOLD if strict else 0.0)
        matcher = SequenceMatcher(autojunk=False)
        matcher.set_seq2(key)
        top: tuple[str, float, str] | None = None
        for k, name in self._candidates(key):
            # A window much shorter or longer than the drug is a different word that
            # happens to share letters ("statin" vs nystatin) or a drug plus its
            # neighbours ("take met formin"). Either way, not this window's match.
            if min(len(k), len(key)) < LENGTH_RATIO * max(len(k), len(key)):
                continue
            matcher.set_seq1(k)
            # Cheap upper bounds first; ratio() is the expensive one.
            if matcher.real_quick_ratio() < floor:
                continue
            if matcher.quick_ratio() < floor:
                continue
            score = matcher.ratio()
            if score >= floor and (top is None or score > top[1]):
                top = (name, score, "fuzzy")
        return top if top is not None else self._by_spine(key, words)

    @staticmethod
    def _is_nonword(text: str, words: int) -> bool:
        """True if `text` is a single token that is not an English word.

        Conservative on every uncertainty: no wordlist, a multi-word window, or anything
        with an apostrophe or hyphen counts as English and keeps the strict threshold.
        """
        if not _ENGLISH or words != 1:
            return False
        t = text.strip().lower()
        return bool(t) and t.isalpha() and t not in _ENGLISH

    def _by_spine(self, key: str, words: int) -> tuple[str, float, str] | None:
        """Last resort: an unambiguous consonant-spine hit on a single word.

        Single-word only, and exact on the spine -- see `skeleton`. The folded lengths still
        have to agree, so a spine does not match a drug twice its length. Scored at the plain
        THRESHOLD because a spine hit is weaker evidence than a fuzzy one; it only ever fires
        where the fuzzy tier already found nothing at all.
        """
        if words != 1 or len(key) < MIN_FUZZY_LEN:
            return None
        spine = _VOWELS.sub("", key)
        if len(spine) < MIN_SKELETON_LEN:
            return None
        name = self._spines.get(spine)
        if name is None:
            return None
        k = fold(name)
        if min(len(k), len(key)) < LENGTH_RATIO * max(len(k), len(key)):
            return None
        return name, THRESHOLD, "spine"

    def _candidates(self, key: str):
        lo = math.ceil(len(key) * LENGTH_RATIO)
        hi = math.floor(len(key) / LENGTH_RATIO)
        for n in range(lo, hi + 1):
            yield from self._blocks.get((key[0], n), ())

    def find(self, text: str) -> list[Correction]:
        """Corrections for `text`, non-overlapping.

        Every 1..MAX_WINDOW word window is scored against the lexicon; see the comments
        inline for how overlapping windows are resolved. A correctly transcribed drug
        scores 1.0 and claims its span without producing a correction, which stops a
        neighbouring window from re-matching half of it.
        """
        words = list(_WORD.finditer(text))
        # (i, size, drug, score) for every window that clears the threshold.
        candidates: list[tuple[int, int, str, float, str]] = []
        for size in range(1, min(MAX_WINDOW, len(words)) + 1):
            for i in range(len(words) - size + 1):
                start, end = words[i].start(), words[i + size - 1].end()
                window = text[start:end]
                hit = self.best(fold(window), words=size, text=window)
                if hit is not None:
                    candidates.append((i, size, hit[0], hit[1], hit[2]))

        def redundant(c: tuple[int, int, str, float, str]) -> bool:
            i, size, drug, score, _tier = c
            return any(
                j >= i and j + s <= i + size and s < size and d == drug and sc >= score
                for j, s, d, sc, _t in candidates
            )

        # Drop a window that only extends a shorter window's match with the same drug and
        # scores no better: "on Metformin" adds nothing to "Metformin", but "a moxy cillin"
        # (exact) does improve on "moxy cillin". Then longest wins, so that
        # "cypro flocks a sin" (ciprofloxacin) beats "cypro" (Cipro) inside it.
        candidates = [c for c in candidates if not redundant(c)]
        candidates.sort(key=lambda c: (-c[1], -c[3]))
        taken = [False] * len(words)
        found: list[Correction] = []
        for i, size, drug, score, tier in candidates:
            if any(taken[i : i + size]):
                continue
            taken[i : i + size] = [True] * size
            start, end = words[i].start(), words[i + size - 1].end()
            heard = text[start:end]
            if heard.lower() != drug.lower():
                found.append(Correction(start, end, heard, drug, score, tier))
        found.sort(key=lambda c: c.start)
        return found

    def correct(self, text: str) -> str:
        out, pos = [], 0
        for c in self.find(text):
            out.append(text[pos : c.start])
            out.append(c.drug)
            pos = c.end
        out.append(text[pos:])
        return "".join(out)
